version: "2"
services:
  dmarc-reports:
    image: antedebaas/dmarc-reports:latest
    volumes:
      - /root/your.env.local:/var/www/html/.env.local:rw
    ports:
        - 0.0.0.0:8080:8080
    environment:
      DATABASE_TYPE: mysql
      DATABASE_HOST: 
      DATABASE_PORT: 3306
      DATABASE_NAME: dmarcreports
      DATABASE_USER: 
      DATABASE_PASSWORD: 
      MAILER_HOST: 
      MAILER_SMTPPORT: 25
      MAILER_IMAPPORT: 993
      MAILER_USER: 
      MAILER_PASSWORD: 
    restart: unless-stopped
